Openram(sram) support added.
merledu/azadi-new pull request #10
Opened 2021-09-28 11:52 UTC by sajjadahmed677

This PR contains ```openram(sram)``` compatible interfaces for ```iccm``` and ```dccm``` with slightly modified directory structure. This resolves #9

2021-09-29 14:08 UTC, zeeshanrafique23 requested changes
Few things need a change.
Rename `brq_core_top` to `ibex_core_top` also check if we could use [ibex_core_top](https://github.com/merledu/azadi-new/blob/main/hw/azadi/rtl/brq_core_top.sv) as it is? The top module of ibex should be at this location `hw/azadi/rtl/brq_core_top.sv`.

2021-09-29 14:12 UTC, zeeshanrafique23 requested changes
Please put `iccm_controller.v` and `uart_rx_prog.v` under folder `hw/azadi/ip/iccm_controller` and `hw/azadi/ip/uart_rx_prog.v` respectively.

2021-09-29 14:14 UTC, zeeshanrafique23 requested changes
Please put `rstmgr.v` in folder `hw/ip/rstmgr`.

2021-09-29 14:20 UTC, zeeshanrafique23 requested changes
Please put `sky130_sram_1kbyte_1rw1r_32x256_8.v` file in folder `hw/vendor/openram` with it's tests benches in `hw/vendor/openram/dv`. It would be great if we can add complete repo of [openram](https://github.com/efabless/sky130_sram_macros) in `hw/vendor/openram/`, make sure to do not copy `.git` or `.github` folder in this case?

2021-09-29 14:23 UTC, zeeshanrafique23 requested changes
Please restore the deleted file `hw/azadi/rtl/testbench.v` and put it under `hw/dv/iverilog/`.

2021-09-30 08:47 UTC, sajjadahmed677 commented
> Please put `iccm_controller.v` and `uart_rx_prog.v` under folder `hw/azadi/ip/iccm_controller` and `hw/azadi/ip/uart_rx_prog.v` respectively.

both modules are used for programming the ```iccm``` in later we will wrap them in single module named as ```programmer```

2021-09-30 08:52 UTC, sajjadahmed677 commented
> Please restore the deleted file `hw/azadi/rtl/testbench.v` and put it under `hw/dv/iverilog/`.

I will add test benches for ```iverilog``` and ```xcelium``` in later update.

2021-09-30 08:54 UTC, sajjadahmed677 commented
> Please put `sky130_sram_1kbyte_1rw1r_32x256_8.v` file in folder `hw/vendor/openram` with it's tests benches in `hw/vendor/openram/dv`. It would be great if we can add complete repo of [openram](https://github.com/efabless/sky130_sram_macros) in `hw/vendor/openram/`, make sure to do not copy `.git` or `.github` folder in this case?

I need to check the ```openram``` repo for that first. i will add dv in next release.

2021-09-30 09:05 UTC, sajjadahmed677 commented
Required changes are done please review them. @zeeshanrafique23

2021-09-30 14:16 UTC, zeeshanrafique23 commented
LGTM, thanks for the follow up.

2021-09-30 14:16 UTC, merged